program IridiumSimulator;

uses
  System.StartUpCopy,
  FMX.Skia,
  FMX.Types,
  FMX.Forms,
  FMX.Styles,
  ufMain in 'ufMain.pas' {frmMain},
  uComplex in '..\..\CommonCode\libRoadRunner\uComplex.pas',
  uEigenvalues in '..\..\CommonCode\libRoadRunner\uEigenvalues.pas',
  uIMSLLib in '..\..\CommonCode\libRoadRunner\uIMSLLib.pas',
  uJVector in '..\..\CommonCode\libRoadRunner\uJVector.pas',
  uMatrix in '..\..\CommonCode\libRoadRunner\uMatrix.pas',
  uRoadRunner.API in '..\..\CommonCode\libRoadRunner\uRoadRunner.API.pas',
  uRoadRunner in '..\..\CommonCode\libRoadRunner\uRoadRunner.pas',
  uRR2DSimpleMatrix in '..\..\CommonCode\libRoadRunner\uRR2DSimpleMatrix.pas',
  uRRList in '..\..\CommonCode\libRoadRunner\uRRList.pas',
  uRRTypes in '..\..\CommonCode\libRoadRunner\uRRTypes.pas',
  uAntimonyTypes in '..\..\libAntimonyAPI\uAntimonyTypes.pas',
  uAntimonyRaw in '..\..\libAntimonyAPI\uAntimonyRaw.pas',
  uAntimonyAPI in '..\..\libAntimonyAPI\uAntimonyAPI.pas',
  RateLaw.Types in '..\..\RateLawChecker\RateLaw.Types.pas',
  RateLaw.Ast in '..\..\RateLawChecker\RateLaw.Ast.pas',
  RateLaw.Parser in '..\..\RateLawChecker\RateLaw.Parser.pas',
  RateLaw.Canonical in '..\..\RateLawChecker\RateLaw.Canonical.pas',
  RateLaw.BuiltInLaws in '..\..\RateLawChecker\RateLaw.BuiltInLaws.pas',
  RateLaw.Diff in '..\..\RateLawChecker\RateLaw.Diff.pas',
  RateLaw.Registry in '..\..\RateLawChecker\RateLaw.Registry.pas',
  RateLaw.Generative in '..\..\RateLawChecker\RateLaw.Generative.pas',
  RateLaw.Bind in '..\..\RateLawChecker\RateLaw.Bind.pas',
  RateLaw.Associate in '..\..\RateLawChecker\RateLaw.Associate.pas',
  RateLaw.Eval in '..\..\RateLawChecker\RateLaw.Eval.pas',
  RateLaw.Dynamic in '..\..\RateLawChecker\RateLaw.Dynamic.pas',
  RateLaw.Report in '..\..\RateLawChecker\RateLaw.Report.pas',
  RateLaw.Static in '..\..\RateLawChecker\RateLaw.Static.pas',
  ufRateLawOptions in 'ufRateLawOptions.pas' {frmRateLawOptions},
  uRateLawModelSource in 'uRateLawModelSource.pas',
  uCommonTypes in 'uCommonTypes.pas',
  uFrameTimeCourse in 'uFrameTimeCourse.pas' {FrameTimeCourse: TFrame},
  uFrameSteadyState in 'uFrameSteadyState.pas' {FrameSteadyState: TFrame},
  uFrameSliderContainer in 'uFrameSliderContainer.pas' {FrameSliderContainer: TFrame},
  uModelSession in 'uModelSession.pas',
  uAnalysisTypes in 'uAnalysisTypes.pas',
  uColorList in 'uColorList.pas',
  uFrameParameterScan in 'uFrameParameterScan.pas' {FrameParameterScan: TFrame},
  uFontHandling in 'uFontHandling.pas',
  FMX.RichEdit.Style in 'RichMemo\FMX.RichEdit.Style.pas',
  FMX.StyledContextMenu in 'RichMemo\FMX.StyledContextMenu.pas',
  SpellChecker in 'RichMemo\SpellChecker.pas',
  Syntax.Code.Antimony in 'RichMemo\Syntax.Code.Antimony.pas',
  Syntax.Code in 'RichMemo\Syntax.Code.pas',
  uBuiltInModels in 'uBuiltInModels.pas',
  uBioModelsCache in 'uBioModelsCache.pas',
  Syntax.Code.Pascal in 'RichMemo\Syntax.Code.Pascal.pas',
  ufBar3DWindow in 'ufBar3DWindow.pas' {frmBar3D},
  U3DBarGraph in '..\T3DBarGraph-main\U3DBarGraph.pas',
  ufAbout in 'ufAbout.pas' {frmAbout},
  SkPlotPaintBox in '..\RhodyComponents\PlottingComponent\Source\SkPlotPaintBox.pas',
  SkPlotPaintBoxRegister in '..\RhodyComponents\PlottingComponent\Source\SkPlotPaintBoxRegister.pas',
  uColorManager in '..\RhodyComponents\PlottingComponent\Source\uColorManager.pas',
  uCSVReaderForPlotter in '..\RhodyComponents\PlottingComponent\Source\uCSVReaderForPlotter.pas',
  uLabelledTrackBar in '..\RhodyComponents\PlottingComponent\Source\uLabelledTrackBar.pas',
  uMathParser in '..\RhodyComponents\PlottingComponent\Source\uMathParser.pas',
  uPlotDefaults in '..\RhodyComponents\PlottingComponent\Source\uPlotDefaults.pas',
  uPlotJsonUtils in '..\RhodyComponents\PlottingComponent\Source\uPlotJsonUtils.pas',
  uPlotMapper in '..\RhodyComponents\PlottingComponent\Source\uPlotMapper.pas',
  uPlotSeries in '..\RhodyComponents\PlottingComponent\Source\uPlotSeries.pas',
  Sim.Meta.Types in '..\..\Antimony_MetaData_Support\Sim.Meta.Types.pas',
  Sim.Meta.Lexer in '..\..\Antimony_MetaData_Support\Sim.Meta.Lexer.pas',
  Sim.Meta.Ast in '..\..\Antimony_MetaData_Support\Sim.Meta.Ast.pas',
  Sim.Meta.Registry in '..\..\Antimony_MetaData_Support\Sim.Meta.Registry.pas',
  Sim.Meta.Parser in '..\..\Antimony_MetaData_Support\Sim.Meta.Parser.pas',
  Sim.Meta.Validate in '..\..\Antimony_MetaData_Support\Sim.Meta.Validate.pas',
  Sim.Meta.Model in '..\..\Antimony_MetaData_Support\Sim.Meta.Model.pas',
  Sim.Meta in '..\..\Antimony_MetaData_Support\Sim.Meta.pas',
  Sim.Meta.Writer in '..\..\Antimony_MetaData_Support\Sim.Meta.Writer.pas',
  Sim.Meta.Python in '..\..\Antimony_MetaData_Support\Sim.Meta.Python.pas',
  Sim.Meta.SedML.Types in '..\..\Antimony_MetaData_Support\Sim.Meta.SedML.Types.pas',
  Sim.Meta.SedML.Export in '..\..\Antimony_MetaData_Support\Sim.Meta.SedML.Export.pas',
  Sim.Meta.Omex in '..\..\Antimony_MetaData_Support\Sim.Meta.Omex.pas',
  uMetaSymbolProvider in 'uMetaSymbolProvider.pas',
  uMetaScriptGen in 'uMetaScriptGen.pas',
  uPreferences in 'uPreferences.pas',
  uMetaExperiments in 'uMetaExperiments.pas',
  uMetaSelector in 'uMetaSelector.pas',
  uMetaSetValues in 'uMetaSetValues.pas',
  uMetaOutput in 'uMetaOutput.pas',
  uFrameMetadata in 'uFrameMetadata.pas' {FrameMetadata: TFrame},
  uMySplitter in 'uMySplitter.pas',
  ufConfigureCVODE in 'ufConfigureCVODE.pas' {frmConfigCVODE},
  ufConfigureSteadyState in 'ufConfigureSteadyState.pas' {frmConfigSteadyState},
  ufPlotEditor in '..\RhodyComponents\PlottingComponent\Source\ufPlotEditor.pas' {FrmPlotEditor};

{$R *.res}

begin
  GlobalUseSkia := True;
  {$IFDEF MACOS}
  //FMX.Types.GlobalUseMetal := False;
  //FMX.Types.GlobalEventDrivenDisplayUpdates := True;
  {$ENDIF}
  Application.Initialize;
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TfrmAbout, frmAbout);
  Application.CreateForm(TFrmPlotEditor, FrmPlotEditor);
  Application.Run;
end.
