unit uMetaScriptGen;

{ Panel settings back OUT to a metadata block.

  The metadata block is a library of presets, and until now it only ever
  travelled one way: the file filled the panels. This is the return leg —
  the user sets a panel up by hand, presses Generate, and the block
  describing what they just did is appended to the model.

  Nothing here formats text by hand. The panels build the same typed
  commands the parser produces, and Sim.Meta.Writer emits them, so a
  generated block is spelled exactly like one that has been round-tripped
  and cannot drift as the format gains keys. That is also why MarkWritten
  exists: the writer emits a key when the user wrote it OR when its value
  differs from the specification's default, so a value that happens to
  equal the default — 'timestart: 0' — is only written if we claim it was
  asked for. }

interface

uses
  System.SysUtils, System.Classes, System.Generics.Collections,
  Sim.Meta, Sim.Meta.Model, Sim.Meta.Writer;

{ Claim AKey as written on ACmd, so the writer emits it even when its
  value equals the default. AAsList picks 'y: [S1]' over 'y: S1' — the
  writer round-trips the two spellings separately. }
procedure MarkWritten(ACmd: TMetaCommandBase; const AKey: string;
                      AAsList: Boolean = False);

{ APrefix followed by the lowest number that collides with nothing in
  AMeta — neither the label itself nor any of APrefix+N+ASuffixes, so a
  caller that will derive further labels from this one can reserve them
  all in a single question. AMeta may be nil (no block yet). }
function UniqueMetaLabel(AMeta: TSimulationMetadata; const APrefix: string;
                         const ASuffixes: array of string): string;

{ ACommands as a block comment ready to append to an Antimony model: one
  command per paragraph, then a prose line naming where it came from.

  Prose and commands may share a comment (spec 3.1), and a file may hold
  any number of blocks — they are processed in file order as if
  concatenated — so appending is always safe and never has to merge with
  a block already there.

  The provenance line goes LAST, which looks backwards and is not. The
  editor's highlighter classifies a comment as metadata from its first
  line with content: '@' there and the whole comment is a metadata block
  however long it runs, anything else and it is ordinary prose to the end.
  Opening with 'Generated by ...' therefore parsed perfectly and rendered
  as a grey wall of text. The format is looser than the highlighter here —
  it takes commands in any order among prose — so the block leads with a
  command and the credit follows it. }
function MetaBlockText(const ACommands: array of TMetaCommandBase;
                       const APanelName, AToolName: string): string;

implementation

procedure MarkWritten(ACmd: TMetaCommandBase; const AKey: string;
                      AAsList: Boolean);
begin
  if (ACmd = nil) or ACmd.WasWritten(AKey) then Exit;
  ACmd.WrittenKeys   := ACmd.WrittenKeys   + [AKey];
  ACmd.WrittenAsList := ACmd.WrittenAsList + [AAsList];
end;

function UniqueMetaLabel(AMeta: TSimulationMetadata; const APrefix: string;
                         const ASuffixes: array of string): string;

  function Taken(const ALabel: string): Boolean;
  var
    C: TMetaCommandBase;
  begin
    Result := False;
    if AMeta = nil then Exit;
    { Against AutoLabel as well as the written one: an unlabelled command
      still answers to a generated 'sim1', and a 'source' may name it. }
    for C in AMeta.Commands do
      if SameText(C.CmdLabel, ALabel) or SameText(C.AutoLabel, ALabel) then
        Exit(True);
  end;

  function AnyTaken(const ABase: string): Boolean;
  var
    S: string;
  begin
    Result := Taken(ABase);
    if Result then Exit;
    for S in ASuffixes do
      if Taken(ABase + S) then
        Exit(True);
  end;

var
  N: Integer;
begin
  N := 1;
  while AnyTaken(APrefix + IntToStr(N)) do
    Inc(N);
  Result := APrefix + IntToStr(N);
end;

function MetaBlockText(const ACommands: array of TMetaCommandBase;
                       const APanelName, AToolName: string): string;
var
  W:     TMetaWriter;
  SB:    TStringBuilder;
  Cmd:   TMetaCommandBase;
  Text:  string;
begin
  Result := '';
  if Length(ACommands) = 0 then Exit;

  W  := TMetaWriter.Create;
  SB := TStringBuilder.Create;
  try
    SB.AppendLine('/*');

    for Cmd in ACommands do
    begin
      { An unknown command has no typed form and comes back empty. None is
        generated here, but the writer's contract allows it, so skip
        rather than emit a blank paragraph. }
      Text := W.CommandToText(Cmd);
      if Trim(Text) = '' then Continue;
      SB.AppendLine(Text);
      SB.AppendLine;
    end;

    { After the commands — see the note on the interface declaration. }
    SB.AppendLine(Format('Generated by %s from the %s panel, %s.',
      [AToolName, APanelName, FormatDateTime('yyyy-mm-dd hh:nn', Now)]));
    SB.AppendLine('*/');
    Result := SB.ToString;
  finally
    SB.Free;
    W.Free;
  end;
end;

end.
